### ISSUE TITLE
Close model button

### ISSUE THREAD

**Issue by odeclas** [paneron/extension-hls#34]
Pretty mundane, but could we have a 'close' button (or perhaps a clear button) on Model Viewer and the two Mapper panes.

**Comment by wkwong-ribose** [comment]
I can put some temporary buttons somewhere for now.
 
In the future, this issue is related to #9. There are many 'open file' actions now. The goal is to make the model loaded only once and its related files (e.g., mapping / report templates / data repositories) can be read automatically without 'opening' again. A consolidated open / close mechanism can be made to make things smoother.
